### ISSUE TITLE
Not working in django 1.10+

### ISSUE THREAD

**Issue by Rested** [LibraryOfCongress/django-tabular-export#2]
because of an error with the aggregate_select attribute not existing on the query, 
fixed in https://github.com/LibraryOfCongress/django-tabular-export/pull/1

**Comment by acdha** [comment]
Closed in https://github.com/LibraryOfCongress/django-tabular-export/commit/0e1aa6392df7b32565624aaab65a7b85df9f689a

Thanks for the fix!
